<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerVg6khk9\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerVg6khk9/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerVg6khk9.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerVg6khk9\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerVg6khk9\appDevDebugProjectContainer([
    'container.build_hash' => 'Vg6khk9',
    'container.build_id' => 'd220e92e',
    'container.build_time' => 1670793565,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerVg6khk9');
