<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerVcabgxp\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerVcabgxp/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerVcabgxp.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerVcabgxp\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerVcabgxp\appDevDebugProjectContainer([
    'container.build_hash' => 'Vcabgxp',
    'container.build_id' => '8588f343',
    'container.build_time' => 1670800917,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerVcabgxp');
