<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerTjt96si\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerTjt96si/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerTjt96si.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerTjt96si\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerTjt96si\appProdProjectContainer([
    'container.build_hash' => 'Tjt96si',
    'container.build_id' => '698002aa',
    'container.build_time' => 1670424190,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerTjt96si');
