<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerCcxs2ug\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerCcxs2ug/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerCcxs2ug.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerCcxs2ug\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerCcxs2ug\appProdProjectContainer([
    'container.build_hash' => 'Ccxs2ug',
    'container.build_id' => '8d8168f6',
    'container.build_time' => 1670411368,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerCcxs2ug');
