<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container7cfprup\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container7cfprup/appProdProjectContainer.php') {
    touch(__DIR__.'/Container7cfprup.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\Container7cfprup\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \Container7cfprup\appProdProjectContainer([
    'container.build_hash' => '7cfprup',
    'container.build_id' => '4f3fe27d',
    'container.build_time' => 1670436032,
], __DIR__.\DIRECTORY_SEPARATOR.'Container7cfprup');
